on: [push]
jobs:
  build-and-deploy:
    env:
      REGISTRY_URL:  kapasrijkubacr.azurecr.io
      SERVICE_NAME: kpjavakubernetes01  
      NAMESPACE: kpjavakubernetes01 
      IMAGE_NAME: kpjavakubernetes01
      APP_NAME: kpjavakubernetes_01
      SECRET_NAME: kpjavakubernetesdockerauth01

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: kapasrijkubacr.azurecr.io
        username: 'kapasrijkubacr'
        password: 's+Hpaz1jpJFcwmq647n+IpLepCicg4G3'
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/java/spring/container/Application" -f  "java/spring/container/Application/Dockerfile" -t  $REGISTRY_URL/$IMAGE_NAME:qwe
        docker push $REGISTRY_URL/$IMAGE_NAME:qwe
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: kpjavakubernetes_0f623
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep $NAMESPACE | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace $NAMESPACE`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: kpjavakubernetes01
        container-registry-url: kapasrijkubacr.azurecr.io
        container-registry-username: 'kapasrijkubacr'
        container-registry-password: 's+Hpaz1jpJFcwmq647n+IpLepCicg4G3'
        secret-name: kpjavakubernetesdockerauth01
       
    - name: Generate Kubernetes Manifest file
      id: manifest-creation
      run: |
        echo  "apiVersion : apps/v1beta1
              kind: Deployment
              metadata:
                name: "$APP_NAME"
              spec:
                replicas: 2
                template:
                  metadata:
                    labels:
                      app: "$APP_NAME"
              spec:
                containers:
                  - name: "$APP_NAME"
                    image: "$REGISTRY_URL/$IMAGE_NAME"
                    ports:
                    - containerPort: aven:3.5.2-jdk-8
                  
                  

                apiVersion: v1
                kind: Service
                metadata:
                    name: "$APP_NAME"
                    labels:
                        app: "$APP_NAME"
                spec:
                    type: LoadBalancer
                    ports:
                    - port: aven:3.5.2-jdk-8
                      targetPort: http
                      protocol: TCP
                      name: http
                    selector:
                        app: "$APP_NAME"
                        
                 "  > manifest_.yml


    - uses: azure/k8s-deploy@v1
      with:
        namespace: kpjavakubernetes01
        manifests: |
          .yml }}}
        images: |
          $REGISTRY_URL/$IMAGE_NAME:abc
        imagepullsecrets: |
          $SECRET_NAME
